name: "Aikido scanner - CI"
on:
  push: # Triggers scan-repo flow for every push to the specified branches
    branches:
      - main  
  workflow_dispatch: # The repository will be scanned on demand
jobs:
  scan-with-local-scanner:
    runs-on:  [self-hosted, sbz]
    environment: aikido
    steps:
      - name: Checkout repository          
        uses: actions/checkout@v4
      - name: Download scanner from nexus
        run: |
          curl --insecure -O "https://frnug01.stago.grp/repository/Blob.Windows.local/test/aikido-local-scanner.exe"   
          dir
      - name: Display folder content 
        run: |
          dir 
      - name: Scan
        run: |
          .\aikido-local-scanner.exe scan . --apikey ${{ secrets.AIKIDO_API_KEY }} --repositoryname WpfApp-NetFramework-Injections --branchname main 
